version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet  # Add the network to db service

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - appnet  # Add the network to pgadmin service

  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=mydb
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["./main"]
    networks:
      - appnet  # Ensure the app is connected to the correct network

volumes:
  postgres_data:

networks:
  appnet:
    driver: bridge
